name: Pre-Code Review

on:
  pull_request:
    types: [opened, synchronize]
  workflow_dispatch:

jobs:
  unit-tests:
    name: Unit Tests and typecheck
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements-dev.txt

      - name: Run unit tests
        run: pytest tests/
      
      - name: Type checks
        run: mypy .

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 black 

      - name: Check formatting with Black
        run: black --check .

      - name: Lint with flake8
        run: flake8 .